// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetProcessListByPortNumber(arg1:string):Promise<Array<models.CmdStruct>>;

export function Greet(arg1:string):Promise<string>;

export function KillProcessByPortNumber(arg1:string):Promise<boolean>;
